### ISSUE TITLE
Readme Organization

### ISSUE THREAD

**Issue by lfarah** [mergesort/UIViewController-Sharing#1]
Hey @mergesort, your library is really interesting.

The only problem I found was the `README.md`, which lacks information.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to do it.

What are your thoughts?

**Comment by mergesort** [comment]
@lfarah I think you meant @mergesort. This library is actually soon to be deprecated, in favor of [Communicado](https://github.com/mergesort/Communicado).

I'll update the README to reflect that at another point in time.

**Comment by lfarah** [comment]
@mergesort hehe I copy and paste this "Lacks information" text to make it faster for me to open issues in iOS libs....

Let me know if you need any help with Communicado, from CocoaPods support to Readme organization. 😉

**Comment by mergesort** [comment]
It will have CocoaPods support, but it's not officially launched yet, so I'm not counting on it. I'll add a better README there when it ships officially.

**Comment by lfarah** [comment]
Let me know when you launch so I can add it on AwesomeiOS!
